server:
  port: 8083
  ssl:
    enabled: false
    certificate: /etc/letsencrypt/live/api.teda.uz/fullchain.pem
    certificate-private-key: /etc/letsencrypt/live/api.teda.uz/privkey.pem
spring:
  datasource:
    url: jdbc:postgresql://185.185.80.245/eventSystems
#    url: jdbc:postgresql://localhost:5432/eventSystems
    username: admin
    password: Turgun1970$
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
telegram:
  bot:
#    username: avantageEvents_bot
#    token: 6189750542:AAHumZZIJbwfwrdBtSwzsTffCCxboIAGVRo
#    username: Uzb_Namaz_Times_bot
#    token: 5082104093:AAEtEN22_VScHuRU7mgdvI8H-1p6v8hn8KU
    username: sms101_bot
    token: 6187531776:AAGMZLtj7n4AupV6rBoDs0PxaHugRtg3dm8
debug: true
page:
  size: 20
company:
  department:
    id : 3