name: Build and host
on:
  push:
    branches: [main]
    paths-ignore:
      - 'src/main/frontend/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build Application
        run: mvn clean install -q -Dspring.profiles.active=test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Package
        uses: appleboy/ssh-action@master
        env:
          PROJECT_PATH: ${{secrets.PROJECT_PATH}}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_PATH
          script: |
            cd $PROJECT_PATH
            git pull origin
            mvn clean install -Dspring.profiles.active=test
  run:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Runing
        uses: appleboy/ssh-action@master
        env:
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
          NAME: ${{ secrets.NAME }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: PROJECT_PATH,NAME
          script: |
            cd $PROJECT_PATH
            if tmux has-session -t $NAME; then
              tmux kill-session -t $NAME
            fi
              tmux new-session -d -s $NAME
            tmux send-keys "mvn spring-boot:run -Dspring-boot.run.profiles=prod" C-m